# -*- coding: utf-8 -*-
"""rulebasedchatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iwzGvD5KBzbCGfd6K5v9ssAGs3BDDnPr
"""

def greet():
    print("Bot: Hello mate! I'm Jarvis, your simple chatbot.")
    print("Bot: You can say things like 'hi', 'how are you', 'bye', etc.")
    print("Bot: Type 'goodbye' to end the conversation.")

def get_response(user_input):
    user_input = user_input.lower()

    if "hi" in user_input or "hello" in user_input:
        return "Hi there! How can I help you today?"
    elif "how are you" in user_input:
        return "I'm just a program, but I'm doing great! Thanks for asking."
    elif "your name" in user_input:
        return "I'm Jarvis, your friendly chatbot!"
    elif "bye" in user_input:
        return "Goodbye! Have a great day!"
    elif "help" in user_input:
        return "You can greet me, ask how I am, ask my name, or say bye."
    else:
        return "I'm sorry, I don't understand that. Try something else or say 'help'."

def chatbot():
    greet()
    while True:
        user_input = input("You: ")
        if user_input.lower() == "exit":
            print("Bot: Exiting chat. Goodbye!")
            break
        response = get_response(user_input)
        print("Bot:", response)


chatbot()